route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'ses'
receivers:
  - name: 'ses'
    email_configs:   #after creation of Amazon SES identity and SMTP Credentials(smarthost, username and password) need to provide below
      - smarthost: 'email-smtp.us-east-1.amazonaws.com:587'
        auth_username: 'your-username'
        auth_password: "your-password"
        from: 'your-from-address'
        to: 'your-to-address'
        headers:
          subject: 'Prometheus Mail Alerts'
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']